# Compute the first n fibonacci numbers
# 0, 1, 1, 2, 3, 5, 8, 13, etc...

def fib(n, a=0, b=1):
    ''' compute the first n "fibonacci-like" numbers.
        other sequences, like the lucas numbers can
        also be generated by changine a and b'''
    out=[]
    for x in range(n):
        a, b = a+b, a
        out.append(b)
    return out

n = 20
fibs = fib(n)
print("The first", n, "fibonacci numbers are:", fibs)
